url: http://patrikwibron.se
title: Patrik Wibron
description: Bloggen för frontendutvecklaren Patrik Wibron. Fokus på användarvänlighet och prestanda.

permalink: /post/:title

future: false
auto: true
server: true

exclude: ["README.md", "config.rb"]
